FROM golang:1.13.6-alpine3.11

RUN set -ex; \
    apk update && apk upgrade && \
    apk add --no-cache bash git openssh \
    gcc wget libc-dev --virtual build-dependencies

RUN go get -u github.com/cosmtrek/air