{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manifest.serviceAccountName" . }}
  labels:
{{ include "manifest.labels" . | nindent 4 }}
{{- end -}}
