version: "3.6"

services:
  github-api:
    build:
      context: github-api
      dockerfile: Dockerfile.dev
    working_dir: /srv/github-api
    volumes:
      - ./github-api:/srv/github-api
    command: air
    links:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    ports:
      - 5432:5432
  
